# Déterminant 

## Propriétés clés du déterminant

1. **Multilinéarité**  
   Le déterminant est **linéaire** par rapport à **chaque ligne ou colonne** prise individuellement.  
   Cela signifie qu'en fixant toutes les autres lignes, si on remplace une ligne par une combinaison linéaire, le déterminant se transforme de manière correspondante.

2. **Changement de signe**  
   Échanger deux lignes (ou colonnes) multiplie le déterminant par $-1$ :
   $$
   \text{Si on échange deux lignes : } \det(A') = -\det(A)
   $$

3. **Proportionnalité**  
   Si une ligne (ou colonne) est multipliée par $k$, alors le déterminant est multiplié par $k$ :
   $$
   \det(A') = k \cdot \det(A)
   $$

4. **Triangularité**  
   Si $A$ est une matrice triangulaire (supérieure ou inférieure), alors :
   $$
   \det(A) = \prod_{i=1}^n a_{ii}
   $$

5. **Produit**  
   Pour deux matrices $A$ et $B$ de même dimension :
   $$
   \det(AB) = \det(A) \cdot \det(B)
   $$

---

## Interprétation géométrique

- **Valeur absolue** :  
  $|\det(A)|$ = facteur d’agrandissement (ou de réduction) **d’aire** (en 2D) ou de **volume** (en 3D) de la transformation linéaire associée à $A$.

- **Signe** :  
  - $\det(A) > 0$ ⇒ orientation préservée  
  - $\det(A) < 0$ ⇒ orientation inversée (symétrie, effet miroir)

- **Cas particulier** :  
  Si $\det(A) = 0$, l’espace est **écrasé** dans une dimension inférieure : la transformation n’est **pas inversible**.


## Exemple 3×3 avec la formule des permutations

On prend la matrice :

$$
A =
\begin{pmatrix}
1 & 2 & 3 \\
0 & 4 & 5 \\
1 & 0 & 6
\end{pmatrix}
$$

---

### Rappel de la formule générale

$$
\det(A) = \sum_{\sigma \in S_3} \mathrm{sgn}(\sigma) \prod_{i=1}^3 a_{i, \sigma(i)}
$$

- $S_3$ = ensemble des **6 permutations** de $\{1, 2, 3\}$  
- $\mathrm{sgn}(\sigma)$ = $+1$ si permutation paire, $-1$ si permutation impaire

---

### Liste des permutations et calcul

1. **$\sigma = (1,2,3)$**  
   $\mathrm{sgn} = +1$  
   Produit : $a_{1,1} \cdot a_{2,2} \cdot a_{3,3} = 1 \cdot 4 \cdot 6 = 24$  
   Contribution : **$+24$**

2. **$\sigma = (1,3,2)$**  
   $\mathrm{sgn} = -1$  
   Produit : $a_{1,1} \cdot a_{2,3} \cdot a_{3,2} = 1 \cdot 5 \cdot 0 = 0$  
   Contribution : **$0$**

3. **$\sigma = (2,1,3)$**  
   $\mathrm{sgn} = -1$  
   Produit : $a_{1,2} \cdot a_{2,1} \cdot a_{3,3} = 2 \cdot 0 \cdot 6 = 0$  
   Contribution : **$0$**

4. **$\sigma = (2,3,1)$**  
   $\mathrm{sgn} = +1$  
   Produit : $a_{1,2} \cdot a_{2,3} \cdot a_{3,1} = 2 \cdot 5 \cdot 1 = 10$  
   Contribution : **$+10$**

5. **$\sigma = (3,1,2)$**  
   $\mathrm{sgn} = +1$  
   Produit : $a_{1,3} \cdot a_{2,1} \cdot a_{3,2} = 3 \cdot 0 \cdot 0 = 0$  
   Contribution : **$0$**

6. **$\sigma = (3,2,1)$**  
   $\mathrm{sgn} = -1$  
   Produit : $a_{1,3} \cdot a_{2,2} \cdot a_{3,1} = 3 \cdot 4 \cdot 1 = 12$  
   Contribution : **$-12$**

---

### Somme des contributions

$$
\det(A) = (+24) + (0) + (0) + (+10) + (0) + (-12)
$$

$$
\det(A) = 24 + 10 - 12 = 22
$$

✅ **Résultat final** :
$$
\boxed{\det(A) = 22}
$$


---

## 1) Déterminant d’une petite matrice

In [1]:
import numpy as np

# Matrice 2x2
A = np.array([[2, 1],
              [0, 3]], dtype=float)

det_A = np.linalg.det(A)
print('Matrice A =\n', A)
print(f'Déterminant de A : {det_A}')


Matrice A =
 [[2. 1.]
 [0. 3.]]
Déterminant de A : 6.0


## 2) Vérification avec le produit des valeurs propres
Propriété utilisée : $\det(A) = \prod_i \lambda_i$.

In [6]:
# Valeurs propres et vérification
eigvals = np.linalg.eigvals(A)
prod_eig = np.prod(eigvals)
print('Valeurs propres de A :', eigvals)
print('Produit des valeurs propres :', prod_eig)
print('Égal au déterminant ?', np.isclose(prod_eig, det_A))


Valeurs propres de A : [2. 3.]
Produit des valeurs propres : 6.0
Égal au déterminant ? True


## 3) Déterminant d’une matrice de covariance (finance)
Interprétation : si $\det(\Sigma) \approx 0$, la covariance est **mal conditionnée** (colinéarité entre actifs).

In [3]:
# Exemple : covariance de 3 actifs
cov_matrix = np.array([[0.09, 0.06, 0.02],
                       [0.06, 0.16, 0.04],
                       [0.02, 0.04, 0.25]], dtype=float)

det_cov = np.linalg.det(cov_matrix)
print('Matrice de covariance =\n', cov_matrix)
print(f'Déterminant de la covariance : {det_cov:.6f}')


Matrice de covariance =
 [[0.09 0.06 0.02]
 [0.06 0.16 0.04]
 [0.02 0.04 0.25]]
Déterminant de la covariance : 0.002588


## 4) Test d’inversibilité
On évite d'inverser en pratique, mais ce test est utile pour le flux logique.

In [4]:
if np.isclose(det_A, 0):
    print('A est singulière → pas d\'inverse.')
else:
    inv_A = np.linalg.inv(A)
    print('Inverse de A =\n', inv_A)


Inverse de A =
 [[ 0.5        -0.16666667]
 [ 0.          0.33333333]]


## 5) Cas symbolique (SymPy) — Déterminant générique 2×2

In [ ]:
import sympy as sp
a, b, c, d = sp.symbols('a b c d')
M = sp.Matrix([[a, b], [c, d]])
det_M = M.det()
display(M)
print('Déterminant symbolique :', det_M)


Matrix([
[a, b],
[c, d]])

Déterminant symbolique : a*d - b*c


---
**Astuce pratique (prod):** privilégier les factorisations (LU/Cholesky/QR) et les solves triangulaires plutôt que l’inversion explicite pour résoudre $Ax=b$.