## Valeurs propres et vecteurs propres

---

### 1. Définition simple (intuitif)

Une **valeur propre** (eigenvalue) et un **vecteur propre** (eigenvector) décrivent un vecteur qui, lorsqu'on lui applique la transformation représentée par une matrice $A$, **reste dans la même direction** (il est simplement étiré ou compressé).

- **Vecteur propre** : vecteur qui ne change pas de direction sous l'action de $A$
- **Valeur propre** : facteur d'étirement/compression associé à ce vecteur

💡 Exemple :  
Si $A \mathbf{v} = 3 \mathbf{v}$, alors :
- $\mathbf{v}$ est un **vecteur propre**
- $3$ est la **valeur propre**

---

### 2. Définition mathématique

Pour une matrice $A \in \mathbb{R}^{n \times n}$, un **vecteur propre** $\mathbf{v} \neq \mathbf{0}$ et une **valeur propre** $\lambda \in \mathbb{R}$ vérifient :

$$
A \mathbf{v} = \lambda \mathbf{v}
$$

Ce qui équivaut à :

$$
(A - \lambda I) \mathbf{v} = \mathbf{0}
$$

Pour qu'il existe une solution non triviale ($\mathbf{v} \neq \mathbf{0}$), il faut :

$$
\det(A - \lambda I) = 0
$$

Cette équation est appelée **équation caractéristique** et permet de trouver les **valeurs propres** $\lambda$.

---

### 3. Propriétés clés

1. Une matrice $n \times n$ a au plus **$n$ valeurs propres** (en comptant les multiplicités).
2. Les **valeurs propres** peuvent être réelles ou complexes (même si $A$ est réelle).
3. La **somme** des valeurs propres = **trace** de $A$ :
   $$
   \text{tr}(A) = \sum_{i=1}^n \lambda_i
   $$
4. Le **produit** des valeurs propres = **déterminant** de $A$ :
   $$
   \det(A) = \prod_{i=1}^n \lambda_i
   $$
5. Les vecteurs propres associés à des valeurs propres **différentes** sont linéairement **indépendants**.

---

### 4. Interprétation géométrique

- En 2D :  
  $A$ peut **étirer** ou **rétrécir** l'espace le long de certaines directions privilégiées (vecteurs propres).
- En 3D :  
  Les vecteurs propres sont les **axes principaux** de la transformation linéaire, et les valeurs propres donnent le **facteur d'échelle** sur chaque axe.
- Si une valeur propre est **nulle** ($\lambda = 0$) :
  - $A$ écrase complètement dans la direction du vecteur propre associé.
- Si une valeur propre est **négative** :
  - Le vecteur est **renversé** (changement d'orientation) en plus d'être étiré/compressé.

---

### 5. Exemple simple

Prenons :
$$
A =
\begin{pmatrix}
2 & 0 \\
0 & 3
\end{pmatrix}
$$

- Équation caractéristique :
$$
\det(A - \lambda I) =
\begin{vmatrix}
2 - \lambda & 0 \\
0 & 3 - \lambda
\end{vmatrix}
= (2 - \lambda)(3 - \lambda) = 0
$$
- **Valeurs propres** : $\lambda_1 = 2$, $\lambda_2 = 3$
- **Vecteurs propres** :
  - Pour $\lambda_1 = 2$ : tous les vecteurs de la forme $(x, 0)$
  - Pour $\lambda_2 = 3$ : tous les vecteurs de la forme $(0, y)$

Ici, $A$ étire :
- Par un facteur 2 dans la direction de l'axe $x$
- Par un facteur 3 dans la direction de l'axe $y$


In [9]:
import numpy as np

np.set_printoptions(precision=4, suppress=True)

# -----------------------------
# Fonctions d'exemples
# -----------------------------

def exemple_diagonale():
    D = np.diag([2, 5, 7])
    vals, vecs = np.linalg.eig(D)
    return D, vals, vecs

def exemple_triangulaire():
    T = np.array([[3, 1, 4],
                  [0, 2, -1],
                  [0, 0, 5]], dtype=float)
    vals, vecs = np.linalg.eig(T)
    return T, vals, vecs

def exemple_projection():
    # Projection sur le plan x-y dans R^3
    P = np.array([[1, 0, 0],
                  [0, 1, 0],
                  [0, 0, 0]], dtype=float)
    vals, vecs = np.linalg.eig(P)
    return P, vals, vecs

def exemple_reflexion():
    # Réflexion de Householder par rapport à l'hyperplan orthogonal à v
    v = np.array([1., 0., 0.])
    H = np.eye(3) - 2 * np.outer(v, v) / np.dot(v, v)
    vals, vecs = np.linalg.eig(H)
    return H, vals, vecs

def exemple_rang1():
    u = np.array([1., 2., 3.])
    v = np.array([4., 5., 6.])
    A = np.outer(u, v)  # Rang 1
    vals, vecs = np.linalg.eig(A)
    return A, vals, vecs

def exemple_orthogonale():
    # Rotation 2D de 90°
    theta = np.pi / 2
    Q = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta),  np.cos(theta)]])
    vals, vecs = np.linalg.eig(Q)
    return Q, vals, vecs

def exemple_symetrique():
    # Matrice de Laplace tridiagonale (symétrique)
    A = np.array([[ 2., -1.,  0.],
                  [-1.,  2., -1.],
                  [ 0., -1.,  2.]])
    vals, vecs = np.linalg.eig(A)
    return A, vals, vecs


# -----------------------------
# Analyse heuristique d'une matrice
# -----------------------------

def est_diagonale(A, tol=1e-12):
    return np.allclose(A, np.diag(np.diag(A)), atol=tol)

def est_triangulaire_superieure(A, tol=1e-12):
    return np.allclose(A, np.triu(A), atol=tol)

def est_triangulaire_inferieure(A, tol=1e-12):
    return np.allclose(A, np.tril(A), atol=tol)

def est_symetrique(A, tol=1e-12):
    return np.allclose(A, A.T, atol=tol)

def est_orthogonale(A, tol=1e-12):
    n, m = A.shape
    if n != m:
        return False
    return np.allclose(A.T @ A, np.eye(n), atol=tol)

def est_projection(A, tol=1e-12):
    # Projection orthogonale si A^2 = A et A symétrique
    return est_symetrique(A, tol) and np.allclose(A @ A, A, atol=tol)

def est_reflexion_householder(A, tol=1e-12):
    # Householder: symétrique + orthogonale + spectre dans {-1, +1} avec au moins un -1
    if not (est_symetrique(A, tol) and est_orthogonale(A, tol)):
        return False
    vals = np.linalg.eigvals(A)
    return np.all(np.isclose(np.abs(vals), 1, atol=1e-10)) and np.any(vals < 0)

def est_rang1(A, tol=1e-12):
    return np.linalg.matrix_rank(A, tol) == 1

def analyser_matrice(A, tol=1e-12):
    n, m = A.shape
    tags = []

    if n == m:
        if est_diagonale(A, tol):
            tags.append("Diagonale")
        if est_triangulaire_superieure(A, tol):
            tags.append("Triangulaire supérieure")
        if est_triangulaire_inferieure(A, tol):
            tags.append("Triangulaire inférieure")
        if est_symetrique(A, tol):
            tags.append("Symétrique réelle")
        if est_orthogonale(A, tol):
            tags.append("Orthogonale")
        if est_projection(A, tol):
            tags.append("Projection orthogonale (A^2=A)")
        if est_reflexion_householder(A, tol):
            tags.append("Réflexion de Householder")
        if est_rang1(A, tol):
            tags.append("Rang 1")
    else:
        # Pas carrée ⇒ pas d'eigenvalues réelles en général (définies pour matrices carrées)
        tags.append("Non carrée (pas de valeurs propres)")

    return tags


# -----------------------------
# Affichage utilitaire
# -----------------------------

def afficher_resultat(nom, A, vals, vecs):
    print("=" * 80)
    print(f"{nom}")
    print("-" * 80)
    print("Matrice :\n", A)
    print("\nValeurs propres :\n", vals)
    print("\nVecteurs propres (colonnes) :\n", vecs)
    print("\nReconnaissance rapide :", analyser_matrice(A))
    print("=" * 80, "\n")


# -----------------------------
# Démo
# -----------------------------
exemples = [
    ("Diagonale",   exemple_diagonale),
    ("Triangulaire", exemple_triangulaire),
    ("Projection orthogonale", exemple_projection),
    ("Réflexion (Householder)", exemple_reflexion),
    ("Rang 1",      exemple_rang1),
    ("Orthogonale", exemple_orthogonale),
    ("Symétrique réelle", exemple_symetrique),
]
for nom, f in exemples:
    A, vals, vecs = f()
    afficher_resultat(nom, A, vals, vecs)
# Exemple perso : remplace par ta matrice
# A_perso = np.array([[...], [...], [...]], dtype=float)
# vals, vecs = np.linalg.eig(A_perso)
# afficher_resultat("Ma matrice", A_perso, vals, vecs)


Diagonale
--------------------------------------------------------------------------------
Matrice :
 [[2 0 0]
 [0 5 0]
 [0 0 7]]

Valeurs propres :
 [2. 5. 7.]

Vecteurs propres (colonnes) :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Reconnaissance rapide : ['Diagonale', 'Triangulaire supérieure', 'Triangulaire inférieure', 'Symétrique réelle']

Triangulaire
--------------------------------------------------------------------------------
Matrice :
 [[ 3.  1.  4.]
 [ 0.  2. -1.]
 [ 0.  0.  5.]]

Valeurs propres :
 [3. 2. 5.]

Vecteurs propres (colonnes) :
 [[ 1.     -0.7071  0.8669]
 [ 0.      0.7071 -0.1576]
 [ 0.      0.      0.4729]]

Reconnaissance rapide : ['Triangulaire supérieure']

Projection orthogonale
--------------------------------------------------------------------------------
Matrice :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]

Valeurs propres :
 [1. 1. 0.]

Vecteurs propres (colonnes) :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Reconnaissance rapide : ['Diagonale', 'Triangulaire 

## Tableau récapitulatif — Valeurs propres simplifiées

| Forme de la matrice                              | Valeurs propres                        | Méthode rapide / Astuce |
|--------------------------------------------------|-----------------------------------------|-------------------------|
| **Diagonale**                                    | Diagonale : $d_1, \dots, d_n$           | Lire directement les éléments diagonaux |
| **Triangulaire** (sup. ou inf.)                  | Diagonale : $t_{11}, \dots, t_{nn}$     | Même astuce que diagonale |
| **Projection orthogonale** ($P^2 = P$)            | $0$ (dim. noyau) et $1$ (dim. image)    | Déterminer dimensions des sous-espaces |
| **Réflexion (Householder)**                      | $-1$ (1 fois), $+1$ ($n-1$ fois)        | $v$ associé à $-1$, reste à $+1$ |
| **Matrice de rang 1** ($A=uv^\top$)              | $v^\top u$ (si $\neq 0$) et $0$ ($n-1$ fois) | Produit scalaire donne la valeur non nulle |
| **Orthogonale** ($Q^\top Q = I$)                  | $\lambda$ avec $|\lambda|=1$            | Modules 1, souvent $\pm 1$ si symétrique |
| **Symétrique réelle** ($A = A^\top$)              | Réelles, base ortho de vecteurs propres | Utiliser diagonalisation orthogonale |
