# 📘 Matrice de Covariance — Théorie, Formule et Exemple Python


## 1. Définition matricielle (cas aléatoire)

Soit un vecteur aléatoire de dimension $n$ :

$$
X = 
\begin{bmatrix}
X_1 \\
X_2 \\
\vdots \\
X_n
\end{bmatrix}
$$

La **matrice de covariance** est définie par :

$$
\Sigma = \mathrm{Cov}(X) = \mathbb{E}\Big[(X - \mu)(X - \mu)^\top\Big]
$$

où $\mu = \mathbb{E}[X]$.

Chaque terme de $\Sigma$ est :  
$$\Sigma_{ij} = \mathrm{Cov}(X_i, X_j)$$



## 2. Formule empirique (à partir de données)

Soit une matrice de données $X$ de taille $T \times n$ :

$$
X = 
\begin{bmatrix}
x_{11} & x_{12} & \cdots & x_{1n} \\
x_{21} & x_{22} & \cdots & x_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
x_{T1} & x_{T2} & \cdots & x_{Tn}
\end{bmatrix}
$$

- $T$ = nombre d’observations  
- $n$ = nombre de variables

Soit $\bar{X}$ le vecteur des moyennes empiriques :

$$
\bar{X} = \frac{1}{T} \sum_{t=1}^T X_t
$$

On définit la matrice **centrée** :

$$
\tilde{X} = X - \mathbf{1}_T \bar{X}^\top
$$

où $\mathbf{1}_T$ est un vecteur colonne de $T$ 1.



### ✅ Formule clé : matrice de covariance empirique

$$
\hat{\Sigma} = \frac{1}{T-1} \tilde{X}^\top \tilde{X}
$$

- Chaque élément $\hat{\Sigma}_{ij}$ est la covariance empirique entre $X_i$ et $X_j$  
- Si $i=j$, on obtient la variance de $X_i$



## 3. Démonstration (passage à la formule empirique)

On part de la définition théorique :

$$
\Sigma = \mathbb{E}[(X - \mu)(X - \mu)^\top]
$$

Dans le cas empirique, on approxime l'espérance par la moyenne des $T$ observations :

$$
\hat{\Sigma} = \frac{1}{T} \sum_{t=1}^T (X_t - \bar{X})(X_t - \bar{X})^\top
$$

où $X_t$ est le vecteur-ligne représentant la $t$-ème observation.

En regroupant toutes les observations dans la matrice centrée $\tilde{X}$ (taille $T \times n$),  
cette somme devient exactement :

$$
\hat{\Sigma} = \frac{1}{T-1} \tilde{X}^\top \tilde{X}
$$

Le dénominateur $T-1$ (et non $T$) provient de la **correction de Bessel**,  
qui garantit un estimateur **non-biaisé** de la covariance.



## 4. Exemple Python


In [1]:

import numpy as np

# Exemple : 100 observations de 3 variables
X = np.random.randn(100, 3)

# Moyenne
mean = X.mean(axis=0)

# Matrice centrée
X_centered = X - mean

# Formule matricielle (covariance)
Sigma = (X_centered.T @ X_centered) / (X.shape[0] - 1)

print("Matrice de covariance calculée manuellement :\n", Sigma)

# Vérification avec NumPy
print("\nMatrice de covariance via numpy.cov :\n", np.cov(X.T))


Matrice de covariance calculée manuellement :
 [[ 1.13968247  0.00944311 -0.02114475]
 [ 0.00944311  1.20404282 -0.05168695]
 [-0.02114475 -0.05168695  1.15140395]]

Matrice de covariance via numpy.cov :
 [[ 1.13968247  0.00944311 -0.02114475]
 [ 0.00944311  1.20404282 -0.05168695]
 [-0.02114475 -0.05168695  1.15140395]]


# 📘 Covariance des résidus en régression linéaire

## 1. Modèle

On considère le modèle de régression linéaire :  

$y = X \beta + \varepsilon, \quad \varepsilon \sim \mathcal{N}(0, \sigma^2 I_n)$

- Estimateur des coefficients (OLS) :  
$\hat{\beta} = (X^\top X)^{-1} X^\top y$

- Résidus :  
$e = y - X \hat{\beta} = (I - H)y$

où  

$H = X (X^\top X)^{-1} X^\top$ est la **matrice hat**.

---

## 2. Variance-Covariance des résidus

La variance-covariance des résidus est :  

$\mathrm{Var}(e) = \sigma^2 (I - H)$

- **Sur la diagonale** :  
$\mathrm{Var}(e_i) = \sigma^2 (1 - h_{ii})$

- **Hors-diagonale** :  
$\mathrm{Cov}(e_i, e_j) = - \sigma^2 h_{ij}, \quad i \neq j$

---

## 3. Estimateur de $\sigma^2$

Comme $\sigma^2$ est inconnu, on l’estime par :  

$\hat{\sigma}^2 = \dfrac{e^\top e}{n - p}$

- $n$ : nombre d’observations  
- $p$ : nombre de variables explicatives (y compris l’intercept si inclus)

---

## 4. Script Python


In [3]:
import numpy as np

# --- Données simulées ---
np.random.seed(0)
n, p = 6, 2
X = np.random.randn(n, p)
beta = np.array([1.5, -0.5])
y = X @ beta + np.random.randn(n) * 0.5

# --- Estimateur OLS ---
beta_hat = np.linalg.inv(X.T @ X) @ X.T @ y
y_hat = X @ beta_hat
resid = y - y_hat

# --- Matrice hat ---
H = X @ np.linalg.inv(X.T @ X) @ X.T

# --- Estimateur sigma^2 ---
sigma2_hat = (resid @ resid) / (n - p)

# --- Matrice de covariance des résidus ---
Var_e = sigma2_hat * (np.eye(n) - H)

print("Résidus :", resid.round(3))
print("sigma^2 estimé :", sigma2_hat.round(3))
print("\nMatrice de covariance des résidus :\n", Var_e.round(3))

Résidus : [ 0.128 -0.091 -0.038  0.033  0.759 -0.131]
sigma^2 estimé : 0.155

Matrice de covariance des résidus :
 [[ 0.098 -0.038 -0.056 -0.03   0.002 -0.009]
 [-0.038  0.054  0.015 -0.006 -0.015 -0.059]
 [-0.056  0.015  0.064 -0.039  0.013  0.028]
 [-0.03  -0.006 -0.039  0.137  0.004  0.005]
 [ 0.002 -0.015  0.013  0.004  0.152 -0.011]
 [-0.009 -0.059  0.028  0.005 -0.011  0.116]]
